server:
  port: 40300
  servlet:
      context-path: /user
spring:
  application:
    name: service-ucenter
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://139.196.200.54:3306/xc_user?characterEncoding=utf-8}
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #\u521D\u59CB\u5EFA\u7ACB\u8FDE\u63A5\u6570\u91CF
      minIdle: 5  #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      maxActive: 20 #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maxWait: 10000  #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u6BEB\u79D2
      testOnBorrow: true #\u7533\u8BF7\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      timeBetweenEvictionRunsMillis: 60000 #\u914D\u7F6E\u95F4\u9694\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684\u65F6\u95F4\uFF08\u5355\u4F4D\u662F\u6BEB\u79D2\uFF09
      minEvictableIdleTimeMillis: 300000  #\u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
eureka:
  client:
    registerWithEureka: true #\uFFFD\uFFFD\uFFFD\uFFFD\u05E2\uFFFD\u1FEA\uFFFD\uFFFD
    fetchRegistry: true #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05BF\uFFFD\uFFFD\uFFFD
    serviceUrl: #Eureka\uFFFD\u037B\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDEureka\uFFFD\uFFFD\uFFFD\uFFFD\u02FD\uFFFD\uFFFD\u043D\uFFFD\uFFFD\uFFFD\uFFFD\u0135\uFFFD\u05B7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u043C\uFFFD\uFFFD\u00F6\uFFFD\uFFFD\u0177\u05B8\uFFFD
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #\uFFFD\uFFFD\uFFFD\u053C\uFFFD\uFFFD\uFFFDip\uFFFD\uFFFD\u05B7\u05E2\uFFFD\u1D7DEureka\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #\u05B8\uFFFD\uFFFD\u02B5\uFFFD\uFFFDid
ribbon:
  MaxAutoRetries: 2 #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDEureka\uFFFD\u043F\uFFFD\uFFFD\uFFFD\uFFFD\u04B5\uFFFD\uFFFD\uFFFD\uFFFD\uD94E\uDF35\uFFFD\uFFFD\u01F7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFDeureka\uFFFD\uFFFD\uFFFD\u04B2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05B1\uFFFD\uFFFD\uFFFD\u07F6\uFFFD\u00B7\uFFFD\uFFFD
  MaxAutoRetriesNextServer: 3 #\uFFFD\u043B\uFFFD\u02B5\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD
  OkToRetryOnAllOperations: false  #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0432\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uDB9B\uDF3D\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDget\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDpost\uFFFD\uFFFDput\uFFFD\u0232\uFFFD\uFFFD\uFFFD\u00FB\uFFFD\uFFFD\u02B5\uFFFD\uFFFD\uFFFD\u0775\u0235\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u01FA\uFFFD\u03A3\uFFFD\u0575\uFFFD,\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03AAfalse
  ConnectTimeout: 5000  #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04F5\u0133\uFFFD\u02B1\u02B1\uFFFD\uFFFD
  ReadTimeout: 6000 #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0133\uFFFD\u02B1\u02B1\uFFFD\uFFFD

# mybatis
mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    type-aliases-package: com.liutaiyue.dao