server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: service-zuul
  redis:
      host: ${REDIS_HOST:139.196.200.54}
      port: ${REDIS_PORT:6379}
      timeout: 5000 #\uFFFD\uFFFD\uFFFD\u04F3\uFFFD\u02B1 \uFFFD\uFFFD\uFFFD\uFFFD
      jedis:
        pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 1
          maxWait: -1 #\uFFFD\uFFFD\uFFFD\u04F3\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD -1\u00FB\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD

zuul:
  routes:
      manage-demo:        #\u8DEF\u7531\u540D\u79F0\uFF0C\u540D\u79F0\u4EFB\u610F\uFF0C\u4FDD\u6301\u6240\u6709\u8DEF\u7531\u540D\u79F0\u552F\u4E00
        path: /que/**
        serviceId: service-que  #\u5FAE\u670D\u52A1\u540D\u79F0\uFF0C\u7F51\u5173\u4F1A\u4ECEeureka\u4E2D\u83B7\u53D6\u8BE5\u670D\u52A1\u540D\u79F0\u4E0B\u7684\u670D\u52A1\u5B9E\u4F8B\u7684\u5730\u5740
        #url: http://www.baidu.com #\u4E5F\u53EF\u6307\u5B9Aurl\uFF0C\u6B64url\u4E5F\u53EF\u4EE5\u662F\u5916\u7F51\u5730\u5740\
        strip-prefix: false #true\uFF1A\u4EE3\u7406\u8F6C\u53D1\u65F6\u53BB\u6389\u524D\u7F00\uFF0Cfalse:\u4EE3\u7406\u8F6C\u53D1\u65F6\u4E0D\u53BB\u6389\u524D\u7F00
        sensitiveHeaders:  #\u9ED8\u8BA4zuul\u4F1A\u5C4F\u853Dcookie\uFF0Ccookie\u4E0D\u4F1A\u4F20\u5230\u4E0B\u6E38\u670D\u52A1\uFF0C\u8FD9\u91CC\u8BBE\u7F6E\u4E3A\u7A7A\u5219\u53D6\u6D88\u9ED8\u8BA4\u7684\u9ED1\u540D\u5355\uFF0C\u5982\u679C\u8BBE\u7F6E\u4E86\u5177\u4F53\u7684\u5934\u4FE1\u606F\u5219\u4E0D\u4F1A\u4F20\u5230\u4E0B\u6E38\u670D\u52A1
        #   ignoredHeaders: \u9ED8\u8BA4\u4E3A\u7A7A\u8868\u793A\u4E0D\u8FC7\u8651\u4EFB\u4F55\u5934



eureka:
  client:
    registerWithEureka: true #\uFFFD\uFFFD\uFFFD\uFFFD\u05E2\uFFFD\u1FEA\uFFFD\uFFFD
    fetchRegistry: true #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05BF\uFFFD\uFFFD\uFFFD
    serviceUrl: #Eureka\uFFFD\u037B\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDEureka\uFFFD\uFFFD\uFFFD\uFFFD\u02FD\uFFFD\uFFFD\u043D\uFFFD\uFFFD\uFFFD\uFFFD\u0135\uFFFD\u05B7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u043C\uFFFD\uFFFD\u00F6\uFFFD\uFFFD\u0177\u05B8\uFFFD
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #\uFFFD\uFFFD\uFFFD\u053C\uFFFD\uFFFD\uFFFDip\uFFFD\uFFFD\u05B7\u05E2\uFFFD\u1D7DEureka\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #\u05B8\uFFFD\uFFFD\u02B5\uFFFD\uFFFDid
ribbon:
  MaxAutoRetries: 2 #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDEureka\uFFFD\u043F\uFFFD\uFFFD\uFFFD\uFFFD\u04B5\uFFFD\uFFFD\uFFFD\uFFFD\uD94E\uDF35\uFFFD\uFFFD\u01F7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFDeureka\uFFFD\uFFFD\uFFFD\u04B2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05B1\uFFFD\uFFFD\uFFFD\u07F6\uFFFD\u00B7\uFFFD\uFFFD
  MaxAutoRetriesNextServer: 3 #\uFFFD\u043B\uFFFD\u02B5\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD
  OkToRetryOnAllOperations: false  #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0432\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uDB9B\uDF3D\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDget\uFFFD\uFFFD\uFFFD\uFFFD\u0523\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDpost\uFFFD\uFFFDput\uFFFD\u0232\uFFFD\uFFFD\uFFFD\u00FB\uFFFD\uFFFD\u02B5\uFFFD\uFFFD\uFFFD\u0775\u0235\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u01FA\uFFFD\u03A3\uFFFD\u0575\uFFFD,\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03AAfalse
  ConnectTimeout: 5000  #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04F5\u0133\uFFFD\u02B1\u02B1\uFFFD\uFFFD
  ReadTimeout: 6000 #\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0133\uFFFD\u02B1\u02B1\uFFFD\uFFFD